# Server settings (ServerProperties)
server:
  #address: wangrui
  port: 8080
  sessionTimeout: 30

# Spring settings
spring:
  thymeleaf:
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://wangrui/~/pinecone;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
